[pytest]
testpaths = tests
pythonpath = .

addopts =
    --cov=app
    --cov-report=term-missing
    --cov-report=xml:.coverage-reports/backend/coverage.xml
    --cov-report=html:.coverage-reports/backend/html
    --cov-fail-under=70
