[pytest]
testpaths = tests
pythonpath = .

addopts =
    --cov=app
    --cov-report=term-missing
    --cov-report=xml:.coverage-reports/coverage.xml
    --cov-report=html:.coverage-reports/html
    --cov-fail-under=80
